version: '2'

services:

    php7.2-apache:
      build:
        context: ./
        args:
          - DB_HOST=mysql
          - DB_PORT=3306
          - DB_DATABASE=homestead
          - DB_USER=homestead
          - DB_PASSWORD=secret
      ports:
        - 8080:80
      networks:
        - backend

    php7.2-cli:
      build:
        context: ./docker/php7.2-cli
      volumes:
        - ./:/var/www/html
      ports:
        - 8000:8000
      tty: true
      networks:
        - backend
    
    install:
      build:
        context: ./docker/php7.2-cli
      volumes:
        - ./:/var/www/html
      networks:
        - backend
      depends_on:
        - mysql
      command: ["wait-for-it.sh", "mysql:3306", "-t", "60", "--", "sh", "docker/php7.2-cli/init.sh"]

    mysql:
      image: mysql:8.0.3
      environment:
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=homestead
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
      # ports:
      #   - "3307:3306"
      networks:
        - backend
      # volumes:
      #   - ./mysql_data:/var/lib/mysql

networks:

    backend:
      driver: "bridge"

